# Generated by Django 6.0 on 2025-12-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_book_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.IntegerField(default=1),
        ),
    ]
