# Generated by Django 6.0 on 2025-12-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_book_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
